name: maria_medic
description: "Application de gestion de maladies."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  file_picker: ^10.0.0
  excel: ^4.0.3
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  fl_chart: ^0.68.0
  flutter_pdfview: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#FAF9F6"   # Blue background
  image: assets/icon.png
  android: true
  ios: true
  fullscreen: true
